bluesky_cases = {
    "pure_text": {"url": "https://bsky.app/profile/junlper.beer/post/3lbv5msligk22",
                  "expected": "bluesky_pure_text.json"},
    "text_with_image": {"url": "https://bsky.app/profile/cinnabarocean.bsky.social/post/3lbqxabem4c2t",
                        "expected": "bluesky_text_with_image.json"},
    "text_with_text_repost": {"url": "https://bsky.app/profile/mcuban.bsky.social/post/3lbuyelaaoc2m",
                              "expected": "bluesky_text_with_text_repost.json"},
    "single_video": {"url": "https://bsky.app/profile/alyankovic.bsky.social/post/3lbxe3bn4sk2r",
                     "expected": "bluesky_single_video.json"},
    "single_video_2": {"url": "https://bsky.app/profile/ufw.bsky.social/post/3lbxfxjne422b",
                       "expected": "bluesky_single_video_2.json"},
    "post_as_first_of_thread": {"url": "https://bsky.app/profile/colehairlesscat.bsky.social/post/3lbxawjfqis2r",
                                "expected": "bluesky_post_as_first_of_thread.json"},
    "post_in_middle_of_thread": {"url": "https://bsky.app/profile/colehairlesscat.bsky.social/post/3lbxawlqzok2r",
                                 "expected": "bluesky_post_in_middle_of_thread.json"},
    "post_as_last_of_thread": {"url": "https://bsky.app/profile/colehairlesscat.bsky.social/post/3lbxawno6pk2r",
                               "expected": "bluesky_post_as_last_of_thread.json"},
}
