"""
Pydantic schema for Firecrawl JSON extraction.

This schema is passed to Firecrawl's LLM extraction via the JsonFormat
format option. It defines the structured data we want extracted from
a webpage, aligned with MetadataItem fields.

Fields excluded from extraction (set programmatically):
  - telegraph_url: generated by our Telegraph publishing service
  - category: derived from URL pattern matching
  - message_type: computed from content length
  - url: already known from the request
"""
from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class ExtractedMediaFile(BaseModel):
    """A media file found in the page content."""

    media_type: str = Field(
        description="Type of media: 'image', 'video', or 'audio'",
    )
    url: str = Field(
        description="Direct URL to the media file",
    )
    original_url: Optional[str] = Field(
        default=None,
        description="Original source URL if the media was embedded from another source",
    )
    caption: Optional[str] = Field(
        default=None,
        description="Caption or alt text for the media",
    )


class ExtractedArticle(BaseModel):
    """
    Structured data extracted from a webpage by Firecrawl's LLM.

    Aligned with MetadataItem fields that an LLM can realistically
    extract from page content.
    """

    title: str = Field(
        default="",
        description="The article or post title",
    )
    author: str = Field(
        default="",
        description="The author name or username",
    )
    author_url: Optional[str] = Field(
        default=None,
        description="URL to the author's profile page",
    )
    text: str = Field(
        default="",
        description=(
            "A short plain-text summary of the content, "
            "suitable for a message preview (max ~500 characters)"
        ),
    )
    content: str = Field(
        default="",
        description=(
            "The main body content of the article as clean HTML. "
            "Include headings, paragraphs, lists, links, and images. "
            "Exclude navigation, ads, sidebars, and comments."
        ),
    )
    media_files: List[ExtractedMediaFile] = Field(
        default_factory=list,
        description="All images, videos, and audio files in the article body",
    )


FIRECRAWL_EXTRACTION_PROMPT = (
    "Extract the main article or post content from this page. "
    "For 'content', return the article body as clean HTML preserving "
    "headings, paragraphs, lists, links, and embedded images. "
    "For 'text', provide a brief plain-text summary (under 500 chars). "
    "For 'media_files', list all images and videos found in the "
    "article body with their direct URLs and any captions. "
    "Ignore navigation, advertisements, sidebars, and comment sections."
)
